server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: auth-service
  config:
    import: "configserver:http://config-server:8888"
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: logistics_user
    password: logistics_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# OAuth2 Configuration
  security:
    oauth2:
      authorizationserver:
        client:
          logistics-client:
            registration:
              client-id: logistics-client
              client-secret: "{noop}logistics-secret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/logistics-client
              scopes:
                - read
                - write

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.logistics.auth: DEBUG
    org.springframework.security: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
    import: "configserver:http://config-server:8888"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/logistics_db}
    username: ${SPRING_DATASOURCE_USERNAME:logistics_user}
    password: ${SPRING_DATASOURCE_PASSWORD:logistics_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics}

logging:
  level:
    com.logistics.auth: ${LOGGING_LEVEL_COM_LOGISTICS:INFO}
    org.springframework.security: INFO
    root: ${LOGGING_LEVEL_ROOT:INFO}
